root: ./docs/
ignore: 
  - ./scripts/
  
redirects:
  blockchain-environments/constants: reference/constants.md
  quick-start/connect: tutorials/quick-start/wormhole-connect/wh-connect.md
  explore-wormhole/gateway/onboard: governance/gateway-onboard.md
